!chore: minimize microcosm ecosystem
MapColonies/microcOSM pull request #141
Opened 2022-08-03 15:59 UTC by melancholiai

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2022-08-03 16:01 UTC, CptSchnitz commented
@melancholiai 
![image](https://user-images.githubusercontent.com/12687466/182655487-1cdc292b-c51b-4fac-91b8-49c7b042ce3d.png)

2022-08-09 11:24 UTC, CptSchnitz requested changes

2022-08-09 11:24 UTC, CptSchnitz commented on cgimap/helm/templates/deployment.yaml
> +          imagePullPolicy: {{ .pullPolicy }}
change to .image.pullPolicy (also in web).

2022-08-09 14:27 UTC, melancholiai commented on cgimap/helm/templates/deployment.yaml
> +          imagePullPolicy: {{ .pullPolicy }}
its done inside a `with .Values.image` clause

2022-08-10 10:20 UTC, CptSchnitz approved these changes

2022-08-14 08:42 UTC, merged