refactor(mod_tile): simplified deeply nested functions
MapColonies/microcOSM pull request #83
Opened 2020-12-09 09:22 UTC by CptSchnitz

2020-12-09 14:53 UTC, syncush requested changes

2020-12-09 14:53 UTC, syncush commented on images/mod-tile/start.py
> +# simplify function
remove

2020-12-09 14:53 UTC, syncush commented on images/mod-tile/start.py
> +        #     rendered_file.write('lastRendered=1')
remove

2020-12-10 11:21 UTC, vitaligi commented on images/mod-tile/start.py
> +    mod_tile_log_path = path.join(base_log_path, rendered_name + log_file_extention)
should `mod_tile_log_path` be renamed to `renderd_log_path`?

2020-12-10 11:21 UTC, vitaligi commented on images/mod-tile/start.py
> +        rendered_file.close()
```python3
with open(file_path, 'w') as rendered_file:
    rendered_file.write('lastRendered=1')
```
is a better way handling file writes

2020-12-14 13:12 UTC, syncush approved these changes

2020-12-14 13:13 UTC, merged